### ISSUE TITLE
Two suggestions for optimization proposal.

### ISSUE THREAD

**Issue by jiahut** [zhulg/ChatGPT_CLI_Rust#1]
1. Can it support streaming output, especially when the text is very long, so that we don't have to wait and can view partial content first?
2. Support Ctrl-c to cancel the query. It is possible to discover that the input is incorrect or the output is not as expected, so it is important to end it as soon as possible and start over.

**Comment by zhulg** [comment]
new code Support Ctrl-c to cancel the request  https://github.com/zhulg/ChatGPT_CLI_Rust/commit/42de76164dfaa569f0edb1f0026b4528d5bde131
